import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/app/components/Footer";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white`}>
        <header className="absolute inset-x-0 top-0 z-50">
          <Navbar textColor={"#fff"} />
        </header>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
